### PR TITLE
Add pre-borg and post-build commands

### PR DESCRIPTION
**Pull request by ianhbell**
Also, I found that the ``shell=True`` argument to the subprocess call fixes the pre-build

### CODE REVIEW

**Comment by guyer** [comment]
I turned `shell=True` off on purpose, because it's [dangerous](https://docs.python.org/3/library/subprocess.html#security-considerations). I will troubleshoot what's going on now, as I thought I'd confirmed it was working for me.

**Comment by ianhbell** [comment]
Sorry I can't figure out how to get post-build and pre-borg commands to register, or whatever the correct actions term is

**Comment by guyer** [comment]
What do you mean by "register"?

As you identified yesterday with `No such file or directory: 'python prepare_build.py'`, the code in @main is evidently buggy, but I don't believe `shell=True` is the solution. ***I need to troubleshoot.***

**Comment by ianhbell** [comment]
I tried to follow the pattern of adding functions for post-build and pre-borg following the pattern you established, but then it complains about unmatching arguments:

image

**Comment by ianhbell** [comment]
So I am sure I a missing a step

**Comment by guyer** [comment]
Oh, I see. I'll take a look at what you've done when I get the chance.

**Comment by guyer** [comment]
Ah. You need to add the inputs to [`ntd2d/action.yml`](https://github.com/usnistgov/NISTtheDocs2Death/blob/main/ntd2d/action.yml), as well. NISTtheDocs2Death is an action that invokes an internal action, because of the dain bramaged way that GitHub Actions makes you have "composite" actions *or* "docker" actions, but not both.

**Comment by ianhbell** [comment]
Ah, that makes some vague sense... I am testing that as we speak.

**Pull request closed without merging**
